export const ENDPOINTS = {
  places: "/places",
  placeDetails: (id: number) => `/places/${id}`,
  placeByCode: (code: string) => `/places/code/${code}`,
  searchPlaces: "/places/search",
  placesByCategory: (id: number) => `/places/category/${id}`,
  placesByProvince: (id: number) => `/places/province/${id}`,
  relatedPlaces: (id: number) => `/places/${id}/related`,
  categories: "/categories",
  categoryByCode: (code: string) => `/categories/code/${code}`,
  login: "/auth/login",
  register: "/auth/register",
  user: "/user",
  favorites: "/favorites",
  statistics: "/statistics",
  placeImages: (id: number) => `/places/${id}/images`,
  placePrimaryImage: (id: number) => `/places/${id}/images/primary`,
  virtualTourImages: (id: number) => `/places/${id}/virtual-tour`,
} as const;
